### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by Niall-5P** [Niall-5P/venv_environment_setup#5]
About Section
1. **View & URL**  
   - Add `about` view and `path('about/', views.about, name='about')`  
2. **Template**  
   - `about/templates/about/about.html` with company story  
   - Include descriptive `<meta>` tags in `<head>` and at least one `<a href="…" rel="noopener">External Resource</a>`  
3. **CSS**  
   - `static/about/css/about.css` containing:  
     ```css
     .about-page header {
       background-image: none !important;
     }
     ```  
   - In `about.html`:  
     ```django
     {% load static %}
     {% block extra_css %}
       <link rel="stylesheet" href="{% static 'about/css/about.css' %}">
     {% endblock %}
     {% block body_class %}about-page{% endblock %}
